run:
  deadline: 2m
  skip-files:
    - ^api_v1_test.go
    - ^api_v2_test.go

linters-settings:
  govet:
    check-shadowing: true
  gocyclo:
    min-complexity: 12
  maligned:
    suggest-new: true
  goconst:
    min-len: 2
    min-occurrences: 3
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - lll
    - gas
    - dupl
    - prealloc
    - wsl
    - nlreturn
    - godox
    - gomnd
    - testpackage
    - paralleltest
    - wrapcheck
    - noctx
    - exhaustivestruct

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same: 0
  exclude:
    - '`\(Client\).newRequest` - `body` always receives `nil`'
  exclude-rules:
    - path: (.+)_test.go
      linters: ["funlen"]
#    - path: